# Generated by Django 5.0.7 on 2024-07-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
